[package]
name = "gurpswasm"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.78", features = ["nightly", "serde-serialize"] }
wasm-bindgen-futures = "0.4.28"
futures = "0.3.19"
js-sys = "0.3.55"
bevy = { git="https://github.com/bevyengine/bevy.git", default-features = false }
bevy_ecs = { git="https://github.com/bevyengine/bevy.git" }
yew = { git = "https://github.com/yewstack/yew.git" }
serde = { version = "1.0.117", features = ["derive"] }

[dependencies.web-sys]
features = [
  "console",
  "Comment",
  "Document",
  "DocumentFragment",
  "DomTokenList",
  "Element",
  "Event",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlCollection",
  "Node",
  "NodeList",
  "Text",
  "Window",
]
version = "0.3.55"